{
 "title": "TCP Traffic",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "srcAS",
    "label": "srcAS",
    "query": "SHOW TAG VALUES FROM \"AS_AS_src_sdports\" WITH KEY = \"srcAS\""
   },
   {
    "name": "dstAS",
    "label": "dstAS",
    "query": "SHOW TAG VALUES FROM \"AS_AS_dst_sdports\" WITH KEY = \"dstAS\""
   },
   {
    "name": "NIC_srcAS",
    "query": "SELECT DISTINCT \"srcAS\" FROM \"AS_NIC_src\""
   },
   {
    "name": "srcport",
    "label": "srcport",
    "query": "SHOW TAG VALUES FROM \"AS_AS_src_sdports\" WITH KEY = \"sport\""
   },
   {
    "name": "dstport",
    "label": "dstport",
    "query": "SHOW TAG VALUES FROM \"AS_AS_src_sdports\" WITH KEY = \"dport\""
   }
  ]
 },
 "panels": [
  {
   "title": "TCP traffic per dstPort (to/from ports of interest)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"bytes\")/(1024*1024) as tcp_bytes FROM \"two_weeks\".\"AS_AS_src_sdports\" WHERE protocol='tcp' AND  $timeFilter GROUP BY  time($__interval), dport fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP traffic from each srcAS (to/from ports of interest)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"bytes\")/(1024*1024) as tcp_bytes FROM \"two_weeks\".\"AS_AS_src_sdports\" WHERE protocol='tcp' AND $timeFilter GROUP BY  time($__interval), srcAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP traffic towards each dstAS (to/from ports of interest)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"bytes\")/(1024*1024) as tcp_bytes FROM \"two_weeks\".\"AS_AS_dst_sdports\" WHERE protocol='tcp' AND $timeFilter GROUP BY  time($__interval), dstAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total TCP traffic from each srcAS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"tcp_bytes\")/(1024*1024) as tcp_bytes FROM \"two_weeks\".\"AS_AS_src\" WHERE $timeFilter GROUP BY  time($__interval), srcAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total TCP traffic towards each dstAS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"tcp_bytes\")/(1024*1024) as tcp_bytes FROM \"two_weeks\".\"AS_AS_dst\" WHERE $timeFilter GROUP BY  time($__interval), dstAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total TCP traffic to each network interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"tcp_bytes\")/(1024*1024) as bytes FROM \"two_weeks\".\"AS_NIC_src\" WHERE $timeFilter GROUP BY  time($__interval), interface_id fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP traffic from NIC_srcAS = $NIC_srcAS to each network interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"tcp_bytes\")/(1024*1024) as bytes FROM \"two_weeks\".\"AS_NIC_src\" WHERE (\"srcAS\" = $NIC_srcAS) AND  $timeFilter GROUP BY  time($__interval), interface_id fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP packets towards any dstAS to dstPort = $dstport",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Kpkts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"packets\")/(1000) AS packets FROM \"AS_AS_dst_sdports\" WHERE protocol='tcp' AND (dport =~ /^$dstport$/) AND $timeFilter GROUP BY time($__interval), dstAS fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP traffic towards dstAS = $dstAS to any dstPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"bytes\")/(1024*1024) AS bytes FROM \"AS_AS_dst_sdports\" WHERE protocol='tcp' AND (dstAS =~ /^$dstAS$/) AND $timeFilter GROUP BY time($__interval), dport fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP traffic from srcAS = $srcAS to any  dstPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"bytes\")/(1024*1024) AS bytes FROM \"AS_AS_src_sdports\" WHERE protocol='tcp' AND (srcAS =~ /^$srcAS$/) AND $timeFilter GROUP BY time($__interval), dport fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP traffic from srcAS = $srcAS from any  srcPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"bytes\")/(1024*1024) AS bytes FROM \"AS_AS_src_sdports\" WHERE protocol='tcp' AND (srcAS =~ /^$srcAS$/) AND $timeFilter GROUP BY time($__interval), sport fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}