{
 "title": "UDP Traffic",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "srcAS",
    "label": "srcAS",
    "query": "SHOW TAG VALUES FROM \"AS_AS_src_sdports\" WITH KEY = \"srcAS\""
   },
   {
    "name": "dstAS",
    "label": "dstAS",
    "query": "SHOW TAG VALUES FROM \"AS_AS_dst_sdports\" WITH KEY = \"dstAS\""
   },
   {
    "name": "NIC_srcAS",
    "query": "SELECT DISTINCT \"srcAS\" FROM \"AS_NIC_src\""
   },
   {
    "name": "srcport",
    "label": "srcport",
    "query": "SHOW TAG VALUES FROM \"AS_AS_src_sdports\" WITH KEY = \"sport\""
   },
   {
    "name": "dstport",
    "label": "dstport",
    "query": "SHOW TAG VALUES FROM \"AS_AS_src_sdports\" WITH KEY = \"dport\""
   }
  ]
 },
 "panels": [
  {
   "title": "UDP traffic per reflection-candidate srcPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"bytes\")/(1024*1024) as udp_bytes FROM \"two_weeks\".\"AS_AS_src_sdports\" WHERE protocol='udp' AND  $timeFilter GROUP BY  time($__interval), sport fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic from each srcAS (reflection-candidate ports)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"bytes\")/(1024*1024) as udp_bytes FROM \"two_weeks\".\"AS_AS_src_sdports\" WHERE protocol='udp' AND $timeFilter GROUP BY  time($__interval), srcAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic towards each dstAS (reflection-candidate ports)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"bytes\")/(1024*1024) as udp_bytes FROM \"two_weeks\".\"AS_AS_dst_sdports\" WHERE protocol='udp' AND $timeFilter GROUP BY  time($__interval), dstAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total UDP traffic from each srcAS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"udp_bytes\")/(1024*1024) as udp_bytes FROM \"two_weeks\".\"AS_AS_src\" WHERE $timeFilter GROUP BY  time($__interval), srcAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total UDP traffic towards each dstAS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"udp_bytes\")/(1024*1024) as udp_bytes FROM \"two_weeks\".\"AS_AS_dst\" WHERE $timeFilter GROUP BY  time($__interval), dstAS fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic to each network interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"udp_bytes\")/(1024*1024) as bytes FROM \"two_weeks\".\"AS_NIC_src\" WHERE $timeFilter GROUP BY  time($__interval), interface_id fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic from NIC_srcAS = $NIC_srcAS to each network interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src",
     "query": "SELECT SUM(\"udp_bytes\")/(1024*1024) as bytes FROM \"two_weeks\".\"AS_NIC_src\" WHERE (\"srcAS\" = $NIC_srcAS) AND  $timeFilter GROUP BY  time($__interval), interface_id fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic from any srcAS with srcPort = $srcport",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src_sdports",
     "query": "SELECT sum(\"bytes\")/(1024*1024) AS \"udp_bytes\" FROM \"two_weeks\".\"AS_AS_src_sdports\" WHERE (\"protocol\" = 'udp' AND \"sport\" =~ /^$srcport$/) AND $timeFilter GROUP BY time($__interval), srcAS fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "protocol", "operator": "=", "value": "udp" },
      { "condition": "AND", "key": "dport", "operator": "=~", "value": "/^$dport$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP traffic towards any dstAS from srcPort = $srcport",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AS_AS_src_sdports",
     "query": "SELECT sum(\"bytes\")/(1024*1024) AS \"udp_bytes\" FROM \"two_weeks\".\"AS_AS_dst_sdports\" WHERE (\"protocol\" = 'udp' AND \"sport\" =~ /^$srcport$/) AND $timeFilter GROUP BY time($__interval), dstAS fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "protocol", "operator": "=", "value": "udp" },
      { "condition": "AND", "key": "dport", "operator": "=~", "value": "/^$dport$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP packets towards any dstAS to dstPort = $dstport",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Kpkts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"packets\")/(1000) AS packets FROM \"AS_AS_dst_sdports\" WHERE protocol='udp' AND (dport =~ /^$dstport$/) AND $timeFilter GROUP BY time($__interval), dstAS fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic towards dstAS = $dstAS to any dstPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"bytes\")/(1024*1024) FROM \"AS_AS_dst_sdports\" WHERE protocol='udp' AND (dstAS =~ /^$dstAS$/) AND $timeFilter GROUP BY time($__interval), dport fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic towards dstAS = $dstAS from any srcPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"bytes\")/(1024*1024) FROM \"AS_AS_dst_sdports\" WHERE protocol='udp' AND (dstAS =~ /^$dstAS$/) AND $timeFilter GROUP BY time($__interval), sport fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic from srcAS = $srcAS to any  dstPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"bytes\")/(1024*1024) FROM \"AS_AS_src_sdports\" WHERE protocol='udp' AND (srcAS =~ /^$srcAS$/) AND $timeFilter GROUP BY time($__interval), dport fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP traffic from srcAS = $srcAS from any  srcPort",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "MBytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"bytes\")/(1024*1024) FROM \"AS_AS_src_sdports\" WHERE protocol='udp' AND (srcAS =~ /^$srcAS$/) AND $timeFilter GROUP BY time($__interval), sport fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}